package modelo;
// Generated 06/06/2020 08:10:10 PM by Hibernate Tools 4.3.1



/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private String nombre;
     private Integer precio;

    public Producto() {
    }

	
    public Producto(String nombre) {
        this.nombre = nombre;
    }
    public Producto(String nombre, Integer precio) {
       this.nombre = nombre;
       this.precio = precio;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Integer precio) {
        this.precio = precio;
    }




}


